### ISSUE TITLE
Very long payloads are not processed in a short time

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [oeg-upm/DeltaCimApp#18]
CIM takes a lot of time to send back a fetched payload that is too long, like the one uploaded in this issue. 
[feidID406.json.zip](https://github.com/oeg-upm/DeltaCimApp/files/4947186/feidID406.json.zip)

**Comment by kostopoulos** [comment]
@AndreaCimminoArriaga , @juancanobenito we will have to resolve this. It occured in a real case scenario. 
Find attached the FEID CIM. FEID is trying to post 2880 values. The size is aproximately 960949KB see line 127 on the attached log

[FEIDCim.log](https://github.com/oeg-upm/DeltaCimApp/files/5346588/FEIDCim.log)

**Comment by AndreaCimminoArriaga** [comment]
@kostopoulos since this is an issue with the xmpp, can't you fetch the data in chunks? this will be much easier and will work for sure. The only solution we could do is add a compress algorithm before exchanging data, but this will not ensure to solve the problem (only increate the root of data size) and it will for sure slow down communications.

**Comment by kostopoulos** [comment]
@AndreaCimminoArriaga  this is our workaround for now but in my hummble opinion we should resolve this and increase
the size limit in terms of both openfire settings and code.

**Comment by AndreaCimminoArriaga** [comment]
@kostopoulos as result of our discussions by email, I think we can close this issue. The limitation of payloads is something that smack has, and is not something we can fix since this is also the nature of xmpp (sending pieces of data rather than big chunks). I'm closing this issue, nevertheless, as workaround you can send the same data compressed and decompress it when received.

**Comment by juancanobenito** [comment]
The message is limited to 1Mb due to an OpenFire message limit. (https://github.com/igniterealtime/Openfire-connectionmanager/blob/master/src/java/org/jivesoftware/multiplexer/net/XMLLightweightParser.java)

Tested adding the property "xmpp.parser.buffer.size" with the value 2048576 in OpenFire. The message limit is 2Mb now.
