### ISSUE TITLE
Support PUT and DELETE methods

### ISSUE THREAD

**Issue by kostopoulos** [oeg-upm/DeltaCimApp#30]
@AndreaCimminoArriaga 
Correct me if I am wrong but right now CIM only supports GET and POST operations, correct?
We would like to use PUT and DELETE endpoints via CIM.

**Comment by AndreaCimminoArriaga** [comment]
Next release will have this features, and thus, CIM will support GET, POST, PUT, PATCH, and DELETE.

Additionally, we have fixed a minor issue that you pointed out. When sending data with POST before a body was mandatory, now it is optional
